name: biobb_workflows
channels:
  - conda-forge
  - bioconda
  - salilab
dependencies:
  - python==3.10
  - biobb_common>=5.2.2
  - biobb_structure_utils>=5.2.1
  - biobb_model>=5.2.1
  - biobb_amber>=5.2.1
  - biobb_chemistry>=5.2.1
  - biobb_io>=5.2.3
  - biobb_pdb_tools>=5.2.1
  - biobb_vs>=5.0.0
  - propka==3.5.1
  - modeller                        # Activate for loop modeling in Protein_preparation
  - mdanalysis
  - biopython<=1.81
  - pip:
    # NBDSoftware forks required for MD_gromacs, Traj_postprocessing, Cavity_analysis:
    - biobb_gromacs @ git+https://github.com/NBDsoftware/biobb_gromacs
    - biobb_analysis @ git+https://github.com/NBDsoftware/biobb_analysis
    - -e .                          # install biobb_workflows itself
