name: eucanshare_wf2
channels:
  - conda-forge
  - bioconda
dependencies:
  - biobb_vs>=3.8.1
  - biobb_common>=3.8.1
  - biobb_structure_utils>=3.8.0
  - biobb_analysis>=3.8.0
  - biobb_gromacs>=3.8.1
  - conda
