name: biobb_pp
channels:
  - salilab
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - acpype=2023.10.27
  - ambertools=22.5
  - arpack=3.7.0
  - attrs=25.3.0
  - biobb_amber=5.0.4
  - biobb_chemistry=5.0.3
  - biobb_common=5.0.0
  - biobb_io=5.0.1
  - biobb_model=5.0.0
  - biobb_pdb_tools=5.0.1
  - biobb_structure_checking=3.13.5
  - biobb_structure_utils=5.0.0
  - biopython=1.85
  - blosc=1.21.6
  - boost-cpp=1.78.0
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.4.26
  - cairo=1.18.0
  - certifi=2025.4.26
  - cffi=1.17.1
  - charset-normalizer=3.4.2
  - contourpy=1.3.2
  - cycler=0.12.1
  - cython=3.1.0
  - fftw=3.3.10
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.58.0
  - freetype=2.13.3
  - h2=4.2.0
  - hdf4=4.2.15
  - hdf5=1.14.4
  - hdf5-1107=1.10.7
  - hpack=4.1.0
  - hyperframe=6.1.0
  - icu=73.2
  - idna=3.10
  - importlib_resources=6.5.2
  - jsonschema=4.23.0
  - jsonschema-specifications=2025.4.1
  - keyutils=1.6.1
  - kiwisolver=1.4.7
  - krb5=1.21.3
  - lcms2=2.17
  - ld_impl_linux-64=2.43
  - lerc=4.0.0
  - libaec=1.1.3
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libcurl=8.13.0
  - libdeflate=1.24
  - libedit=3.1.20250104
  - libev=4.33
  - libexpat=2.7.0
  - libffi=3.4.6
  - libfreetype=2.13.3
  - libfreetype6=2.13.3
  - libgcc=15.1.0
  - libgcc-ng=15.1.0
  - libgfortran=15.1.0
  - libgfortran-ng=15.1.0
  - libgfortran5=15.1.0
  - libglib=2.84.1
  - libgomp=15.1.0
  - libiconv=1.18
  - libjpeg-turbo=3.1.0
  - liblapack=3.9.0
  - liblzma=5.8.1
  - liblzma-devel=5.8.1
  - libnetcdf=4.9.2
  - libnghttp2=1.64.0
  - libnsl=2.0.1
  - libopenblas=0.3.29
  - libpng=1.6.47
  - libsqlite=3.49.2
  - libssh2=1.11.1
  - libstdcxx=15.1.0
  - libstdcxx-ng=15.1.0
  - libtiff=4.7.0
  - libuuid=2.38.1
  - libwebp-base=1.5.0
  - libxcb=1.17.0
  - libxcrypt=4.4.36
  - libxml2=2.12.7
  - libzip=1.11.2
  - libzlib=1.3.1
  - lz4-c=1.10.0
  - matplotlib-base=3.10.3
  - modeller=10.6
  - munkres=1.1.4
  - ncurses=6.5
  - netcdf-fortran=4.6.1
  - numpy=1.26.4
  - openbabel=3.1.1
  - openjpeg=2.5.3
  - openssl=3.5.0
  - packaging=25.0
  - packmol=20.16.1
  - pandas=2.2.3
  - parmed=4.3.0
  - pcre2=10.45
  - pdb-tools=2.5.0
  - perl=5.32.1
  - pillow=11.2.1
  - pip=25.1.1
  - pixman=0.46.0
  - pkgutil-resolve-name=1.3.10
  - propka=3.5.1
  - psutil=7.0.0
  - pthread-stubs=0.4
  - pycparser=2.22
  - pyparsing=3.2.3
  - pysocks=1.7.1
  - python=3.10.0
  - python-dateutil=2.9.0.post0
  - python-tzdata=2025.2
  - python_abi=3.10
  - pytz=2025.2
  - pyyaml=6.0.2
  - qhull=2020.2
  - readline=8.2
  - referencing=0.36.2
  - requests=2.32.3
  - rpds-py=0.24.0
  - scipy=1.15.2
  - setuptools=80.1.0
  - six=1.17.0
  - snappy=1.2.1
  - sqlite=3.49.2
  - tk=8.6.13
  - typing_extensions=4.13.2
  - tzdata=2025b
  - unicodedata2=16.0.0
  - urllib3=2.4.0
  - wheel=0.45.1
  - xmltodict=0.14.2
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.6
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxrender=0.9.12
  - xorg-libxt=1.3.1
  - xz=5.8.1
  - xz-gpl-tools=5.8.1
  - xz-tools=5.8.1
  - yaml=0.2.5
  - zipp=3.21.0
  - zlib=1.3.1
  - zstandard=0.23.0
  - zstd=1.5.7
  - pip:
      - amberlite==22.0
      - amberutils==21.0
      - mmpbsa-py==16.0
      - packmol-memgen==1.2.3rc0
      - pdb4amber==22.0
      - pytraj==2.0.6
      - sander==22.0
