name: biobb_pp
channels:
  - conda-forge
  - bioconda
  - salilab
dependencies:
  - python==3.10
  - modeller                        # Activate if you want to use Modeller
  - propka==3.5.1
  - biobb_io>=5.0.0
  - biobb_common>=5.0.0
  - biobb_structure_utils>=5.0.0
  - biobb_model>=5.0.0
  - biobb_amber>=5.0.3
  - biobb_chemistry>=5.0.3
  - biobb_pdb_tools>=5.0.0
