name: biobb_ca
channels:
  - conda-forge
  - bioconda
dependencies:
  - python==3.10
  - biobb_vs>=5.0.0
  - biobb_common>=5.0.0
  - biobb_analysis>=5.0.1
  - biobb_gromacs>=5.0.0
  - biobb_structure_utils>=5.0.0
  - biopython<=1.81
  - mdanalysis