name: biobb_pp_refinement
channels:
  - conda-forge
  - bioconda
  - salilab
dependencies:
  - biobb_common>=4.0.0
  - biobb_structure_utils>=4.0.0
  - biobb_model>=4.0.0
  - biobb_gromacs>=4.0.0
  - biobb_analysis>=4.0.0
