name: biobb_md
channels:
  - conda-forge
  - bioconda
  - salilab
dependencies:
  - python==3.10
  - biobb_common==5.0.0
  - biobb_structure_utils>=5.0.0
  - biobb_model>=5.0.0
  - biobb_gromacs>=5.0.0      # Needs NBDSoftware version
  - biobb_amber>=5.0.3
  - biobb_analysis>=5.0.1     # Needs NBDSoftware version