name: biobb_pp_docking
channels:
  - conda-forge
  - bioconda
dependencies:
  - python==3.10.0
  - biobb_common>=4.0.0   
  - biopython>=1.80
  - zip
  - pandas
  - scipy
  - matplotlib

# Add --pwd flag to singularity exec command in biobb_common.py after installing! 
# Add biobb_pydock.pth (with path to biobb_pydock) to site-packages folder after installing!