name: biobb_pp
channels:
  - conda-forge
  - bioconda
  - salilab
dependencies:
  - python==3.10
  - modeller                        # Activate if you want to use Modeller
  - propka==3.5.1
  - biobb_io==5.2.3
  - biobb_common==5.2.2
  - biobb_structure_utils==5.2.1
  - biobb_model==5.2.1
  - biobb_amber==5.2.1
  - biobb_chemistry==5.2.1
  - biobb_pdb_tools==5.2.1
