name: eucanshare_wf1
channels:
  - conda-forge
  - bioconda
dependencies:
  - biobb_io>=3.7.0
  - biobb_common>=3.7.0
  - biobb_structure_utils>=3.7.0
  - biobb_chemistry>=3.7.0
  - biobb_model>=3.7.0
  - biobb_md>=3.7.0
  - biobb_analysis>=3.7.0
  - conda
