name: single_protein_wf2
channels:
  - conda-forge
  - bioconda
dependencies:
  - biobb_vs>=4.0.0
  - biobb_common>=4.0.0
  - biobb_structure_utils>=4.0.0
  - biobb_analysis>=4.0.0
  - biobb_gromacs>=4.0.0
  - conda
