name: biobb_sumd
channels:
  - anaconda
  - conda-forge
  - bioconda
dependencies:
  - python 3.10
  - mdanalysis
  - scipy
  - biobb_gromacs>=4.0.0
  - biobb_analysis>=4.0.0
  - biobb_common>=4.0.0
  - conda

