name: sumd_analyzer
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - python=3.10
  - pyyaml
  - seaborn
  - mdanalysis
  - barnaba
  - scipy
  - ambertools
  - tqdm
  - numpy>=1.25.0
