name: ligand_parameterization
channels:
  - conda-forge
  - bioconda
dependencies:
  - python==3.10
  - biobb_common>=5.0.0
  - biobb_chemistry>=5.0.3
  - biobb_structure_utils>=5.0.0
  - biobb_amber>=5.0.3
